name: main

on:
  [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install dependencies
      run: python -m pip install --upgrade pip

    - name: lint
      run: |
        # Note: no q2lint here, since this isn't an official QIIME 2 product
        pip install -q flake8
        flake8

  doc-build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - name: create conda testing env
        run: conda create -q -y -p ./test-env

      - name: install dependencies
        run: |
          conda install -p ./test-env -q -y \
            -c conda-forge \
            -c bioconda \
            -c defaults \
            --override-channels sphinx=4.3.1 pip

      - name: install pip dependencies
        shell: bash -l {0}
        run: |
          conda activate ./test-env
          pip install -U "jupyter-book>=0.7.0b"
          pip install git+https://github.com/qiime2/sphinx-ext-qiime2

      - name: build book
        run: conda run -p ./test-env jb build book/

      - name: save built book
        uses: actions/upload-artifact@v2
        with:
          name: book
          path: book/_build/html