name: main

on:
  # build on all PRs, but only trigger push builds on `main`
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install dependencies
      run: python -m pip install --upgrade pip

    - name: lint
      run: |
        pip install -q flake8
        flake8

  doc-build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8

    - name: install latest QIIME 2 core distro (staging)
      run: |
        envFile=qiime2-latest-py38-linux-conda.yml
        wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/$envFile
        conda env create -q -p ./test-env --file $envFile

    - name: install dependencies
      run: |
        conda install -p ./test-env -q -y \
          -c conda-forge \
          -c bioconda \
          -c defaults \
          --override-channels pip

    - name: install pip dependencies
      shell: bash -l {0}
      run: |
        conda activate ./test-env
        pip install -U "jupyter-book"
        pip install git+https://github.com/qiime2/sphinx-ext-qiime2

    - name: build book
      run: conda run -p ./test-env jb build book/

    - name: save built book
      uses: actions/upload-artifact@v2
      with:
        name: book
        path: book/_build/html
