name: main

on:
  # build on all PRs, but only trigger push builds on `main`
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: lint
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JSCPD: false
        DEFAULT_BRANCH: main

  doc-build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8

    - name: install latest QIIME 2 core distro (staging)
      run: |
        envFile=qiime2-latest-py38-linux-conda.yml
        wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/$envFile
        conda env create -q -p ./test-env --file $envFile

    - name: install dependencies
      run: |
        conda install -p ./test-env -q -y \
          -c conda-forge \
          -c bioconda \
          -c defaults \
          --override-channels pip

    - name: install pip dependencies
      shell: bash -l {0}
      run: |
        conda activate ./test-env
        pip install -r book/requirements.txt

    - name: build book
      env:
        Q2DOC_HTML_BASEURL: https://gregcaporaso.github.io/2022.1-faes-tutorial/
      run: conda run -p ./test-env jb build book/

    - name: deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book/_build/html
